//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForeignBooksServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://aspharmony-production.up.railway.app/", ConfigurationName="ForeignBooksServiceReference.BooksServicePortType")]
    public interface BooksServicePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://aspharmony-production.up.railway.app/BooksService/GetBook", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ForeignBooksServiceReference.GetBookResponse1> GetBookAsync(ForeignBooksServiceReference.GetBookRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://aspharmony-production.up.railway.app/BooksService/GetAllBooks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ForeignBooksServiceReference.GetAllBooksResponse> GetAllBooksAsync(ForeignBooksServiceReference.GetAllBooksRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://aspharmony-production.up.railway.app/BooksService/CreateBook", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ForeignBooksServiceReference.CreateBookResponse1> CreateBookAsync(ForeignBooksServiceReference.CreateBookRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://aspharmony-production.up.railway.app/BooksService/UpdateBook", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ForeignBooksServiceReference.UpdateBookResponse1> UpdateBookAsync(ForeignBooksServiceReference.UpdateBookRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://aspharmony-production.up.railway.app/BooksService/DeleteBook", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ForeignBooksServiceReference.DeleteBookResponse1> DeleteBookAsync(ForeignBooksServiceReference.DeleteBookRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://aspharmony-production.up.railway.app/")]
    public partial class GetBookRequest
    {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://aspharmony-production.up.railway.app/")]
    public partial class Chapter
    {
        
        private int indexField;
        
        private string titleField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://aspharmony-production.up.railway.app/")]
    public partial class Book
    {
        
        private int idField;
        
        private string titleField;
        
        private string descriptionField;
        
        private string imageUrlField;
        
        private Chapter[] chaptersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ImageUrl
        {
            get
            {
                return this.imageUrlField;
            }
            set
            {
                this.imageUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Chapters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public Chapter[] Chapters
        {
            get
            {
                return this.chaptersField;
            }
            set
            {
                this.chaptersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://aspharmony-production.up.railway.app/")]
    public partial class GetBookResponse
    {
        
        private Book bookField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Book book
        {
            get
            {
                return this.bookField;
            }
            set
            {
                this.bookField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://aspharmony-production.up.railway.app/", Order=0)]
        public ForeignBooksServiceReference.GetBookRequest GetBookRequest;
        
        public GetBookRequest1()
        {
        }
        
        public GetBookRequest1(ForeignBooksServiceReference.GetBookRequest GetBookRequest)
        {
            this.GetBookRequest = GetBookRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://aspharmony-production.up.railway.app/", Order=0)]
        public ForeignBooksServiceReference.GetBookResponse GetBookResponse;
        
        public GetBookResponse1()
        {
        }
        
        public GetBookResponse1(ForeignBooksServiceReference.GetBookResponse GetBookResponse)
        {
            this.GetBookResponse = GetBookResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://aspharmony-production.up.railway.app/")]
    public partial class GetAllBooksRequest
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBooksRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://aspharmony-production.up.railway.app/", Order=0)]
        public ForeignBooksServiceReference.GetAllBooksRequest GetAllBooksRequest;
        
        public GetAllBooksRequest1()
        {
        }
        
        public GetAllBooksRequest1(ForeignBooksServiceReference.GetAllBooksRequest GetAllBooksRequest)
        {
            this.GetAllBooksRequest = GetAllBooksRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBooksResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBooksResponse", Namespace="https://aspharmony-production.up.railway.app/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("books", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ForeignBooksServiceReference.Book[] GetAllBooksResponse1;
        
        public GetAllBooksResponse()
        {
        }
        
        public GetAllBooksResponse(ForeignBooksServiceReference.Book[] GetAllBooksResponse1)
        {
            this.GetAllBooksResponse1 = GetAllBooksResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://aspharmony-production.up.railway.app/")]
    public partial class CreateBookRequest
    {
        
        private Book bookField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Book book
        {
            get
            {
                return this.bookField;
            }
            set
            {
                this.bookField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://aspharmony-production.up.railway.app/")]
    public partial class CreateBookResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBookRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://aspharmony-production.up.railway.app/", Order=0)]
        public ForeignBooksServiceReference.CreateBookRequest CreateBookRequest;
        
        public CreateBookRequest1()
        {
        }
        
        public CreateBookRequest1(ForeignBooksServiceReference.CreateBookRequest CreateBookRequest)
        {
            this.CreateBookRequest = CreateBookRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBookResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://aspharmony-production.up.railway.app/", Order=0)]
        public ForeignBooksServiceReference.CreateBookResponse CreateBookResponse;
        
        public CreateBookResponse1()
        {
        }
        
        public CreateBookResponse1(ForeignBooksServiceReference.CreateBookResponse CreateBookResponse)
        {
            this.CreateBookResponse = CreateBookResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://aspharmony-production.up.railway.app/")]
    public partial class UpdateBookRequest
    {
        
        private Book bookField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Book book
        {
            get
            {
                return this.bookField;
            }
            set
            {
                this.bookField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://aspharmony-production.up.railway.app/")]
    public partial class UpdateBookResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBookRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://aspharmony-production.up.railway.app/", Order=0)]
        public ForeignBooksServiceReference.UpdateBookRequest UpdateBookRequest;
        
        public UpdateBookRequest1()
        {
        }
        
        public UpdateBookRequest1(ForeignBooksServiceReference.UpdateBookRequest UpdateBookRequest)
        {
            this.UpdateBookRequest = UpdateBookRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBookResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://aspharmony-production.up.railway.app/", Order=0)]
        public ForeignBooksServiceReference.UpdateBookResponse UpdateBookResponse;
        
        public UpdateBookResponse1()
        {
        }
        
        public UpdateBookResponse1(ForeignBooksServiceReference.UpdateBookResponse UpdateBookResponse)
        {
            this.UpdateBookResponse = UpdateBookResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://aspharmony-production.up.railway.app/")]
    public partial class DeleteBookRequest
    {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://aspharmony-production.up.railway.app/")]
    public partial class DeleteBookResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBookRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://aspharmony-production.up.railway.app/", Order=0)]
        public ForeignBooksServiceReference.DeleteBookRequest DeleteBookRequest;
        
        public DeleteBookRequest1()
        {
        }
        
        public DeleteBookRequest1(ForeignBooksServiceReference.DeleteBookRequest DeleteBookRequest)
        {
            this.DeleteBookRequest = DeleteBookRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBookResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://aspharmony-production.up.railway.app/", Order=0)]
        public ForeignBooksServiceReference.DeleteBookResponse DeleteBookResponse;
        
        public DeleteBookResponse1()
        {
        }
        
        public DeleteBookResponse1(ForeignBooksServiceReference.DeleteBookResponse DeleteBookResponse)
        {
            this.DeleteBookResponse = DeleteBookResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface BooksServicePortTypeChannel : ForeignBooksServiceReference.BooksServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class BooksServicePortTypeClient : System.ServiceModel.ClientBase<ForeignBooksServiceReference.BooksServicePortType>, ForeignBooksServiceReference.BooksServicePortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BooksServicePortTypeClient() : 
                base(BooksServicePortTypeClient.GetDefaultBinding(), BooksServicePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BooksServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BooksServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(BooksServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), BooksServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BooksServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BooksServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BooksServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BooksServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BooksServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ForeignBooksServiceReference.GetBookResponse1> ForeignBooksServiceReference.BooksServicePortType.GetBookAsync(ForeignBooksServiceReference.GetBookRequest1 request)
        {
            return base.Channel.GetBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<ForeignBooksServiceReference.GetBookResponse1> GetBookAsync(ForeignBooksServiceReference.GetBookRequest GetBookRequest)
        {
            ForeignBooksServiceReference.GetBookRequest1 inValue = new ForeignBooksServiceReference.GetBookRequest1();
            inValue.GetBookRequest = GetBookRequest;
            return ((ForeignBooksServiceReference.BooksServicePortType)(this)).GetBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ForeignBooksServiceReference.GetAllBooksResponse> ForeignBooksServiceReference.BooksServicePortType.GetAllBooksAsync(ForeignBooksServiceReference.GetAllBooksRequest1 request)
        {
            return base.Channel.GetAllBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<ForeignBooksServiceReference.GetAllBooksResponse> GetAllBooksAsync(ForeignBooksServiceReference.GetAllBooksRequest GetAllBooksRequest)
        {
            ForeignBooksServiceReference.GetAllBooksRequest1 inValue = new ForeignBooksServiceReference.GetAllBooksRequest1();
            inValue.GetAllBooksRequest = GetAllBooksRequest;
            return ((ForeignBooksServiceReference.BooksServicePortType)(this)).GetAllBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ForeignBooksServiceReference.CreateBookResponse1> ForeignBooksServiceReference.BooksServicePortType.CreateBookAsync(ForeignBooksServiceReference.CreateBookRequest1 request)
        {
            return base.Channel.CreateBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<ForeignBooksServiceReference.CreateBookResponse1> CreateBookAsync(ForeignBooksServiceReference.CreateBookRequest CreateBookRequest)
        {
            ForeignBooksServiceReference.CreateBookRequest1 inValue = new ForeignBooksServiceReference.CreateBookRequest1();
            inValue.CreateBookRequest = CreateBookRequest;
            return ((ForeignBooksServiceReference.BooksServicePortType)(this)).CreateBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ForeignBooksServiceReference.UpdateBookResponse1> ForeignBooksServiceReference.BooksServicePortType.UpdateBookAsync(ForeignBooksServiceReference.UpdateBookRequest1 request)
        {
            return base.Channel.UpdateBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<ForeignBooksServiceReference.UpdateBookResponse1> UpdateBookAsync(ForeignBooksServiceReference.UpdateBookRequest UpdateBookRequest)
        {
            ForeignBooksServiceReference.UpdateBookRequest1 inValue = new ForeignBooksServiceReference.UpdateBookRequest1();
            inValue.UpdateBookRequest = UpdateBookRequest;
            return ((ForeignBooksServiceReference.BooksServicePortType)(this)).UpdateBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ForeignBooksServiceReference.DeleteBookResponse1> ForeignBooksServiceReference.BooksServicePortType.DeleteBookAsync(ForeignBooksServiceReference.DeleteBookRequest1 request)
        {
            return base.Channel.DeleteBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<ForeignBooksServiceReference.DeleteBookResponse1> DeleteBookAsync(ForeignBooksServiceReference.DeleteBookRequest DeleteBookRequest)
        {
            ForeignBooksServiceReference.DeleteBookRequest1 inValue = new ForeignBooksServiceReference.DeleteBookRequest1();
            inValue.DeleteBookRequest = DeleteBookRequest;
            return ((ForeignBooksServiceReference.BooksServicePortType)(this)).DeleteBookAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BooksServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BooksServicePort))
            {
                return new System.ServiceModel.EndpointAddress("https://aspharmony-production.up.railway.app/BooksService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BooksServicePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.BooksServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BooksServicePortTypeClient.GetEndpointAddress(EndpointConfiguration.BooksServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            BooksServicePort,
        }
    }
}
