//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JokesServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://aspharmony-production.up.railway.app/", ConfigurationName="JokesServiceReference.JokesServicePortType")]
    public interface JokesServicePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://aspharmony-production.up.railway.app/JokesService/AddNumbers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JokesServiceReference.AddNumbersResponse1> AddNumbersAsync(JokesServiceReference.AddNumbersRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://aspharmony-production.up.railway.app/JokesService/GenerateJoke", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JokesServiceReference.GenerateJokeResponse1> GenerateJokeAsync(JokesServiceReference.GenerateJokeRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://aspharmony-production.up.railway.app/JokesService/GetJokes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JokesServiceReference.GetJokesResponse> GetJokesAsync(JokesServiceReference.GetJokesRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://aspharmony-production.up.railway.app/")]
    public partial class AddNumbersRequest
    {
        
        private int aField;
        
        private int bField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int a
        {
            get
            {
                return this.aField;
            }
            set
            {
                this.aField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int b
        {
            get
            {
                return this.bField;
            }
            set
            {
                this.bField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://aspharmony-production.up.railway.app/")]
    public partial class AddNumbersResponse
    {
        
        private int sumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int sum
        {
            get
            {
                return this.sumField;
            }
            set
            {
                this.sumField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNumbersRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://aspharmony-production.up.railway.app/", Order=0)]
        public JokesServiceReference.AddNumbersRequest AddNumbersRequest;
        
        public AddNumbersRequest1()
        {
        }
        
        public AddNumbersRequest1(JokesServiceReference.AddNumbersRequest AddNumbersRequest)
        {
            this.AddNumbersRequest = AddNumbersRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNumbersResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://aspharmony-production.up.railway.app/", Order=0)]
        public JokesServiceReference.AddNumbersResponse AddNumbersResponse;
        
        public AddNumbersResponse1()
        {
        }
        
        public AddNumbersResponse1(JokesServiceReference.AddNumbersResponse AddNumbersResponse)
        {
            this.AddNumbersResponse = AddNumbersResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://aspharmony-production.up.railway.app/")]
    public partial class GenerateJokeRequest
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://aspharmony-production.up.railway.app/")]
    public partial class GenerateJokeResponse
    {
        
        private string jokeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string joke
        {
            get
            {
                return this.jokeField;
            }
            set
            {
                this.jokeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateJokeRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://aspharmony-production.up.railway.app/", Order=0)]
        public JokesServiceReference.GenerateJokeRequest GenerateJokeRequest;
        
        public GenerateJokeRequest1()
        {
        }
        
        public GenerateJokeRequest1(JokesServiceReference.GenerateJokeRequest GenerateJokeRequest)
        {
            this.GenerateJokeRequest = GenerateJokeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateJokeResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://aspharmony-production.up.railway.app/", Order=0)]
        public JokesServiceReference.GenerateJokeResponse GenerateJokeResponse;
        
        public GenerateJokeResponse1()
        {
        }
        
        public GenerateJokeResponse1(JokesServiceReference.GenerateJokeResponse GenerateJokeResponse)
        {
            this.GenerateJokeResponse = GenerateJokeResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://aspharmony-production.up.railway.app/")]
    public partial class GetJokesRequest
    {
        
        private int countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJokesRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://aspharmony-production.up.railway.app/", Order=0)]
        public JokesServiceReference.GetJokesRequest GetJokesRequest;
        
        public GetJokesRequest1()
        {
        }
        
        public GetJokesRequest1(JokesServiceReference.GetJokesRequest GetJokesRequest)
        {
            this.GetJokesRequest = GetJokesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJokesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetJokesResponse", Namespace="https://aspharmony-production.up.railway.app/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("jokes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] GetJokesResponse1;
        
        public GetJokesResponse()
        {
        }
        
        public GetJokesResponse(string[] GetJokesResponse1)
        {
            this.GetJokesResponse1 = GetJokesResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface JokesServicePortTypeChannel : JokesServiceReference.JokesServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class JokesServicePortTypeClient : System.ServiceModel.ClientBase<JokesServiceReference.JokesServicePortType>, JokesServiceReference.JokesServicePortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public JokesServicePortTypeClient() : 
                base(JokesServicePortTypeClient.GetDefaultBinding(), JokesServicePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.JokesServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JokesServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(JokesServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), JokesServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JokesServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(JokesServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JokesServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(JokesServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JokesServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JokesServiceReference.AddNumbersResponse1> JokesServiceReference.JokesServicePortType.AddNumbersAsync(JokesServiceReference.AddNumbersRequest1 request)
        {
            return base.Channel.AddNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<JokesServiceReference.AddNumbersResponse1> AddNumbersAsync(JokesServiceReference.AddNumbersRequest AddNumbersRequest)
        {
            JokesServiceReference.AddNumbersRequest1 inValue = new JokesServiceReference.AddNumbersRequest1();
            inValue.AddNumbersRequest = AddNumbersRequest;
            return ((JokesServiceReference.JokesServicePortType)(this)).AddNumbersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JokesServiceReference.GenerateJokeResponse1> JokesServiceReference.JokesServicePortType.GenerateJokeAsync(JokesServiceReference.GenerateJokeRequest1 request)
        {
            return base.Channel.GenerateJokeAsync(request);
        }
        
        public System.Threading.Tasks.Task<JokesServiceReference.GenerateJokeResponse1> GenerateJokeAsync(JokesServiceReference.GenerateJokeRequest GenerateJokeRequest)
        {
            JokesServiceReference.GenerateJokeRequest1 inValue = new JokesServiceReference.GenerateJokeRequest1();
            inValue.GenerateJokeRequest = GenerateJokeRequest;
            return ((JokesServiceReference.JokesServicePortType)(this)).GenerateJokeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JokesServiceReference.GetJokesResponse> JokesServiceReference.JokesServicePortType.GetJokesAsync(JokesServiceReference.GetJokesRequest1 request)
        {
            return base.Channel.GetJokesAsync(request);
        }
        
        public System.Threading.Tasks.Task<JokesServiceReference.GetJokesResponse> GetJokesAsync(JokesServiceReference.GetJokesRequest GetJokesRequest)
        {
            JokesServiceReference.GetJokesRequest1 inValue = new JokesServiceReference.GetJokesRequest1();
            inValue.GetJokesRequest = GetJokesRequest;
            return ((JokesServiceReference.JokesServicePortType)(this)).GetJokesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.JokesServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.JokesServicePort))
            {
                return new System.ServiceModel.EndpointAddress("https://aspharmony-production.up.railway.app/JokesService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return JokesServicePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.JokesServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return JokesServicePortTypeClient.GetEndpointAddress(EndpointConfiguration.JokesServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            JokesServicePort,
        }
    }
}
